$(document).on 'turbolinks:load', ->
  $('.corp_identities').each (i, input) ->
    new Awesomplete(input, {
      list: [
        'Haas-Bioroid: Engineering the Future',
        'Haas-Bioroid: Stronger Together',
        'Cerebral Imaging: Infinite Frontiers',
        'Custom Biotics: Engineered for Success',
        'NEXT Design: Guarding the Net',
        'The Foundry: Refining the Process',
        'Cybernetics Division: Humanity Upgraded',
        'Haas-Bioroid: Architects of Tomorrow',
        'Seidr Laboratories: Destiny Defined',
        'Jinteki: Personal Evolution',
        'Jinteki: Replicating Perfection',
        'Harmony Medtech: Biomedical Pioneer',
        'Nisei Division: The Next Generation',
        'Tennin Institute: The Secrets Within',
        'Industrial Genomics: Growing Solutions',
        'Jinteki Biotech: Life Imagined',
        'Chronos Protocol: Selective Mind-mapping',
        'Palana Foods: Sustainable Growth',
        'Jinteki: Potential Unleashed',
        'AgInfusion: New Miracles for a New World',
        'NBN: Making News',
        'NBN: The World is Yours*',
        'Near-Earth Hub: Broadcast Center',
        'Haarpsichord Studios: Entertainment Unleashed',
        'SYNC: Everything, Everywhere',
        'New Angeles Sol: Your News',
        'Spark Agency: Worldswide Reach',
        'Harishchandra Ent.: Where You\'re the Star',
        'NBN: Controlling the Message',
        'Weyland Consortium: Building a Better World',
        'Weyland Consortium: Because We Built It',
        'GRNDL: Power Unleashed',
        'Blue Sun: Powering the Future',
        'Argus Security: Protection Guaranteed',
        'Gagarin Deep Space: Expanding the Horizon',
        'Titan Transnational: Investing In Your Future',
        'Weyland Consortium: Builder of Nations',
        'Jemison Astronautics: Sacrifice. Audacity. Success.',
        'Skorpios Defense Systems: Persuasive Power'
      ],
      sort: ->
        false
    })
  $('.runner_identities').each (i, input) ->
    new Awesomplete(input, {
      list: [
        'Noise: Hacker Extraordinaire',
        'Whizzard: Master Gamer',
        'Reina Roja: Freedom Fighter',
        'Quetzal: Free Spirit',
        'Edward Kim: Humanity\'s Hammer',
        'MaxX: Maximum Punk Rock',
        'Valencia Estevez: The Angel of Cayambe',
        'Null: Whistleblower',
        'Omar Keung: Conspiracy Theorist',
        'Alice Merchant: Clan Agitator',
        'Gabriel Santiago: Consummate Professional',
        'Andromeda: Dispossessed Ristie',
        'Iain Stirling: Retired Spook',
        'Ken "Express" Tenma: Disappeared Clone',
        'Silhouette: Stealth Operative',
        'Leela Patel: Trained Pragmatist',
        'Armand "Geist" Walker: Tech Lord',
        'Laramy Fisk: Savvy Investor',
        'Nero Severn: Information Broker',
        'Khan: Savvy Skiptracer',
        'Los: Data Hijacker',
        'Steve Cambridge: Master Grifter',
        'Kate "Mac" McCaffrey: Digital Tinker',
        'Chaos Theory: Wunderkind',
        'Rielle "Kit" Peddler: Transhuman',
        'The Professor: Keeper of Knowledge',
        'Exile: Streethawk',
        'Nasir Meidan: Cyber Explorer',
        'Hayley Kaplan: Universal Scholar',
        'Jesminder Sareen: Girl Behind the Curtain',
        'Ele "Smoke" Scovak: Cynosure of the Net',
        'Ayla "Bios" Rahim: Simulant Specialist',
        'Apex: Invasive Predator',
        'Adam: Compulsive Hacker',
        'Sunny Lebeau: Security Specialist'
      ],
      sort: ->
        false
    })
